-- 코드를 입력하세요
SELECT ANIMAL_ID, NAME, 
CASE 
    WHEN LOCATE('Neutered', SEX_UPON_INTAKE) > 0 OR LOCATE('Spayed', SEX_UPON_INTAKE)
        THEN 'O'
    ELSE 'X'
END
AS '중성화'
FROM ANIMAL_INS AI
ORDER BY ANIMAL_ID